
spring.application.name=MoneyManagement
spring.profiles.active=dev
server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
management.endpoints.web.exposure.include=health,info
logging.level.com.example.MoneyManagement=INFO