spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=false
spring.mail.default-encoding=UTF-8

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

spring.data.redis.database=0
spring.data.redis.timeout=60000
spring.data.redis.client-type=lettuce

spring.cache.type=redis
spring.cache.cache-names=users,categories,incomes,expenses,dashboard

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd

logging.level.org.springframework.security=WARN
logging.level.com.example.MoneyManagement=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

management.endpoints.web.exposure.include=health,info

spring.main.banner-mode=off
spring.output.ansi.enabled=never





spring.datasource.url=jdbc:postgresql://ep-steep-sunset-atuuy3jg-pooler.c-9.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner 
spring.datasource.password=npg_nQNTqL5B8Mmr
jwt.secret=${JWT_SECRET}
spring.mail.username=nenavathlalsing@gmail.com
spring.mail.password=svpc jdip wyph ndtn
cloudinary.cloud-name= gutqwqbr
cloudinary.api-key= 787461477147566
cloudinary.api-secret=9aOH8LGCsX7HZ8YjUBj1RFd0OUI
spring.data.redis.host=nose-aftermath-ivory-17616.db.redis.io 
spring.data.redis.port=13896 
spring.data.redis.username=default
spring.data.redis.password=GT9KVoU9ELsGt9kGemzTNPnLhefF4RFW 